# Docker Compose file for ViniPlay
# Version 3.8 is a modern, stable version of the Compose file format.
version: "3.8"

services:
  # Define the main application service.
  viniplay:
    # Build from the Dockerfile in the current directory.
    # We use build instead of image so changes to the Dockerfile are applied.
    build: .
    
    # Set a consistent name for the container for easy management.
    container_name: viniplay
    
    # Map port 8998 on your host machine to port 8998 inside the container.
    # This makes the web player accessible at http://localhost:8998.
    ports:
      - "8998:8998"
      
    # Define the restart policy.
    # 'unless-stopped' ensures the container automatically restarts if it crashes,
    # but not when you manually stop it.
    restart: unless-stopped
    
    # NEW: Add a volume for persistent data.
    # This maps the './viniplay-data' directory on your host to the '/data'
    # directory inside the container. All M3U, EPG, and settings files
    # will be stored here, persisting across container restarts and updates.
    volumes:
      - ./viniplay-data:/data
