# This GitHub Actions workflow automates building and pushing your Docker image.
#
# It pushes to two different container registries:
# 1. GitHub Container Registry (ghcr.io)
# 2. Docker Hub (docker.io)
#
# TRIGGERS:
# 1. On a push to the 'main' branch:
#    - The image will be tagged as 'latest'.
# 2. Manually, via the 'workflow_dispatch' event for any other branch or tag.
#
name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub ContainerRegistry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags and labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
            ${{ secrets.DOCKERHUB_USERNAME }}/viniplay
          tags: |
            # Tag with the PR number when a pull request is opened or updated.
            type=ref,event=pr
            
            # Tag with branch name on push to a branch.
            type=ref,event=branch

            # Creates the 'latest' tag when a push is made to the default branch (main).
            type=raw,value=latest,enable={{is_default_branch}}

            # Creates version tags when a git tag is pushed (e.g., v1.2.3 -> 1.2.3).
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Push on main branch pushes or any manual run. 
          # The original condition works because pull_request events are no longer a trigger.
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
